name: call-share

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  get-vars:
    uses: Thhhomees/git-testing-2/.github/workflows/share-vars.yml@main
    secrets: inherit

  print-vars:
    needs: get-vars
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Shared Variable: ${{ needs.get-vars.outputs.variable_value }}"